### ISSUE TITLE
 Code block vanishes with commonmarker 0.18.x

### ISSUE THREAD

**Issue by scivola** [sandfoxme/commonmarker-rouge#4]
I have the following problem.
https://github.com/gjtorikian/commonmarker/issues/85

**Comment by arokettu** [comment]
Partially addressed in #3

**Comment by arokettu** [comment]
@scivola if you can, please use 0.17 or earlier for now

**Comment by arokettu** [comment]
Fixed in 1.5.0

**Comment by scivola** [comment]
I appreciate it!
